# Generated by Django 4.1.5 on 2023-03-08 11:52

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('short_description', models.CharField(blank=True, help_text='Макс. длина: 140 символов. Если не заполнено, то первые 140 символов Полного описания (без обрезания слов)', max_length=140, null=True, verbose_name='Краткое описание')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('is_popular', models.BooleanField(default=False, help_text="Будет отображаться в разделе 'Популярные категории' на главной странице", verbose_name='Популярно')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(auto_now=True, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('in_delivery', 'Доставляется'), ('complete', 'Завершен')], default='new', max_length=12, verbose_name='Статус')),
                ('complete', models.BooleanField(default=False, help_text="Кнопка 'Сделать заказ' была нажата", verbose_name='Сделан')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('description', django_quill.fields.QuillField(blank=True, help_text='Разрешено использование HTML-тэгов, напр. &#60;br>, &#60;strong>, &#60;i>, &#60;u>', null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Главное Изображение')),
                ('active', models.BooleanField(default=True, help_text='Только опубликованные товары будут отображены на сайте', verbose_name='Опубликовать')),
                ('is_popular', models.BooleanField(default=False, help_text="Будет отображаться в разделе 'Популярные товары' на главной странице", verbose_name='Популярно')),
                ('category', models.ManyToManyField(to='store.category', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Город')),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='Индекс')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Покупатель')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'Адрес Доставки',
                'verbose_name_plural': 'Адреса Доставки',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Будут отображены на странице описания товара', upload_to='', verbose_name='Доп. Изображения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Доп. Изображение',
                'verbose_name_plural': 'Доп. Изображения',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказанный Товар',
                'verbose_name_plural': 'Заказанные Товары',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Баннер')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание (необязательно)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Отображать ли на сайте', verbose_name='Включено')),
                ('category', models.ForeignKey(blank=True, help_text='Возможна либо категория, либо товар', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория')),
                ('product', models.ForeignKey(blank=True, help_text='Возможна либо категория, либо товар', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'товар или категорию',
                'verbose_name_plural': 'Карусель',
            },
        ),
    ]
